{
  "formatVersion": "1.1",
  "component": {
    "url": "../../awesome-image/1.0.0/awesome-image-1.0.0.module",
    "group": "awesome.image",
    "module": "awesome-image",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "awesome-image.aar",
          "url": "awesome-image-android-1.0.0.aar",
          "size": 118246,
          "sha512": "ede0104f2e0640912c5f78dc9662fa3e1b22be056ea605b4005d9205007374fc60e57de7bfbc526527ee9edb2ca6d62076f3fd48fa3f209d824e120484648e97",
          "sha256": "9e9b9362216902fa5308099878371c76b4a4d2f0f13b55c8f3f26d90c83dc2d8",
          "sha1": "5d33b5d2f5b908f209e9d2bd15d130314de60d49",
          "md5": "39cd5e66e8d8135dd6c5c716063ad983"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "awesome-image.aar",
          "url": "awesome-image-android-1.0.0.aar",
          "size": 118246,
          "sha512": "ede0104f2e0640912c5f78dc9662fa3e1b22be056ea605b4005d9205007374fc60e57de7bfbc526527ee9edb2ca6d62076f3fd48fa3f209d824e120484648e97",
          "sha256": "9e9b9362216902fa5308099878371c76b4a4d2f0f13b55c8f3f26d90c83dc2d8",
          "sha1": "5d33b5d2f5b908f209e9d2bd15d130314de60d49",
          "md5": "39cd5e66e8d8135dd6c5c716063ad983"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
