{
  "formatVersion": "1.1",
  "component": {
    "url": "../../awesome-image/1.0.0/awesome-image-1.0.0.module",
    "group": "awesome.image",
    "module": "awesome-image",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "awesome-image.aar",
          "url": "awesome-image-android-1.0.0.aar",
          "size": 118031,
          "sha512": "9f8fcda05312d1284325cf421553dc48dabf56672641a04a1b3dee29414dad747339f1a821dbe274538d742cd53f69bb47ad48f0a538610afabe0ee33c54485a",
          "sha256": "c0038cb198ab2ff4f7887ddc61d37be66bf3b4a30749d28e199fc862576e5345",
          "sha1": "11b7fe26feb4eb48c0371215fc699c7bcc3c721d",
          "md5": "e3ab4a295414b6e5e7e62732aa983711"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "awesome-image.aar",
          "url": "awesome-image-android-1.0.0.aar",
          "size": 118031,
          "sha512": "9f8fcda05312d1284325cf421553dc48dabf56672641a04a1b3dee29414dad747339f1a821dbe274538d742cd53f69bb47ad48f0a538610afabe0ee33c54485a",
          "sha256": "c0038cb198ab2ff4f7887ddc61d37be66bf3b4a30749d28e199fc862576e5345",
          "sha1": "11b7fe26feb4eb48c0371215fc699c7bcc3c721d",
          "md5": "e3ab4a295414b6e5e7e62732aa983711"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
