{
  "formatVersion": "1.1",
  "component": {
    "url": "../../awesome-image/1.0.0/awesome-image-1.0.0.module",
    "group": "awesome.image",
    "module": "awesome-image",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "awesome-image.aar",
          "url": "awesome-image-android-1.0.0.aar",
          "size": 115645,
          "sha512": "e6309959b265d6e8eade96e27935e1fafe88d07b0bb66c0e27907488fd0fc7c4fb0bb91f89cfa18549097b8ea764ec3ee8592f3900c38f7b4ff726b961d6a494",
          "sha256": "c9fe6de4e8c563f9176010f388f05d8067ccaf8076ab6bc2c42724529bd8bc18",
          "sha1": "a9dc32f4e3932940ab653fc4ba50635052577948",
          "md5": "f3932640c99b0eaee72c4b2c0c07c6a3"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "awesome-image.aar",
          "url": "awesome-image-android-1.0.0.aar",
          "size": 115645,
          "sha512": "e6309959b265d6e8eade96e27935e1fafe88d07b0bb66c0e27907488fd0fc7c4fb0bb91f89cfa18549097b8ea764ec3ee8592f3900c38f7b4ff726b961d6a494",
          "sha256": "c9fe6de4e8c563f9176010f388f05d8067ccaf8076ab6bc2c42724529bd8bc18",
          "sha1": "a9dc32f4e3932940ab653fc4ba50635052577948",
          "md5": "f3932640c99b0eaee72c4b2c0c07c6a3"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
