{
  "formatVersion": "1.1",
  "component": {
    "group": "awesome.image",
    "module": "awesome-image",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "awesome-image-metadata.jar",
          "url": "awesome-image-1.0.0.jar",
          "size": 9153,
          "sha512": "d5eb7af27d9ec70d5db2d9af0e0b4213e2cc17a6b873fe21254778528ab0aeb963bcb7f038fbb53c3e60db53e64551918b5ebed13a5d63a077ad6339f0925e6f",
          "sha256": "07e4fe4ba84e1b711ca131afdee7408a1ae9733616011ac9c88949607c571b64",
          "sha1": "5372d4af0a9fa7dee7affcf81c84c89e9bdd8286",
          "md5": "6c56de16f8efa0de576bd39bbd24f6dd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../awesome-image-android/1.0.0/awesome-image-android-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../awesome-image-android/1.0.0/awesome-image-android-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../awesome-image-android/1.0.0/awesome-image-android-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iosarm64/1.0.0/awesome-image-iosarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iosarm64/1.0.0/awesome-image-iosarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iosarm64/1.0.0/awesome-image-iosarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iosarm64/1.0.0/awesome-image-iosarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iossimulatorarm64/1.0.0/awesome-image-iossimulatorarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iossimulatorarm64/1.0.0/awesome-image-iossimulatorarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iossimulatorarm64/1.0.0/awesome-image-iossimulatorarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../awesome-image-iossimulatorarm64/1.0.0/awesome-image-iossimulatorarm64-1.0.0.module",
        "group": "awesome.image",
        "module": "awesome-image-iossimulatorarm64",
        "version": "1.0.0"
      }
    }
  ]
}
